name: Build and release

on:
  push:
    branches:
      - pipeline

jobs:
  build-and-release:
    name: Deploy rules to all organisations
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - uses: actions/setup-go@v2
        with:
          go-version: 1.17.0
      - name: run make
        run: make
