name: Build and release

on:
  push:
    branches:
      - pipeline

jobs:
  build-and-release:
    name: Deploy rules to all organisations
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Set up Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@master

      - name: run make
        run: make
