name: Build and release
on:
  push:
    branches:
      - staging
jobs:
  build-and-release:
    name: build-and-release-staging
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - uses: actions/setup-go@v2
        with:
          go-version: 1.17.5
      - name: run make
        run: make
      - name: Set env
        run: echo "VERSION=$(semver get alpha)" >> $GITHUB_ENV
      - uses: "marvinpinto/action-automatic-releases@latest"
        with:
          repo_token: "${{ secrets.GITHUB_TOKEN }}"
          prerelease: true
          title: "log4j scanner ${{ env.VERSION }} alpha"
          files: |
            release/*
      - name: Slack Notification
        uses: rtCamp/action-slack-notify@v2
        env:
          SLACK_WEBHOOK: ${{ secrets.SLACK_WEBHOOK }}