name: Build and release

on:
  push:
    branches:
      - main

jobs:
  build-and-release:
    name: build-and-release
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - uses: actions/setup-go@v2
        with:
          go-version: 1.17.5
      - name: run make
        run: make
      - name: Set env
        run: echo "VERSION=$(semver get alpha)" >> $GITHUB_ENV
      - uses: "marvinpinto/action-automatic-releases@latest"
        with:
          repo_token: "${{ secrets.GITHUB_TOKEN }}"
          automatic_release_tag: "latest"
          prerelease: false
          title: "log4j scanner ${{ env.VERSION }}"
          files: |
            release/*
